baseURL = "https://your-domain.com"
languageCode = "zh-cn"
title = "私人博客"
author = "博主"

# 隐私设置 - 禁止搜索引擎收录
enableRobotsTXT = true
disableKinds = ["rss", "sitemap"]

# 内容设置
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableEmoji = true

# Markdown设置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    noClasses = false

# SEO设置 - 禁止索引
[params]
  description = "一个极简的私人博客"
  keywords = []
  robots = "noindex, nofollow, noarchive, nosnippet"
  
# 隐私配置
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
